/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.components;

import data.model.ServiceCredit;
import java.awt.Color;
import themes.Theme;

/**
 *
 * @author root
 */
public class ServiceCreditItem extends javax.swing.JPanel {

    /**
     * Creates new form ServiceCreditItem
     */
    
    private final ServiceCredit serviceCredit;
    private final int index;
    
    
    public ServiceCreditItem(int index, ServiceCredit serviceCredit) {
        initComponents();
        
        this.serviceCredit = serviceCredit;
        this.index = index;
        
        setDisplay();
    }
    
    private void setDisplay(){
        lbl1.setText(" "+serviceCredit.getOrderNo());
        lbl2.setText("  "+serviceCredit.getMemorandum());
        
        if(index%2==1){
            this.setBackground(Theme.PRIMARY.COLOR.background_secondary);
           
        }else{
            this.setBackground(new Color(204, 230, 192));
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbl1.setFont(Theme.PRIMARY.FONT.tableFontDefault(12)
        );
        lbl1.setText("Order No");
        lbl1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        lbl1.setMaximumSize(new java.awt.Dimension(130, 40));
        lbl1.setMinimumSize(new java.awt.Dimension(130, 40));
        lbl1.setPreferredSize(new java.awt.Dimension(130, 40));
        add(lbl1, java.awt.BorderLayout.WEST);

        lbl2.setFont(Theme.PRIMARY.FONT.tableFontDefault(12)
        );
        lbl2.setText("Memorandum");
        add(lbl2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
