/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.components;

import data.controllers.UserController;
import data.model.User;
import frames.listener.UserItemListener;
import java.awt.Color;
import themes.Theme;
import java.sql.SQLException;

/**
 *
 * @author root
 */
public class UserItem extends javax.swing.JPanel {

    /**
     * Creates new form UserItem
     */
    Theme primary = Theme.PRIMARY;
    User user;
    int index;
    UserItemListener listener;
    
    UserController controller = new UserController();

    public UserItem(UserItemListener listener,int index, User user) {
        initComponents();

        this.user = user;
        this.index = index;
        this.listener = listener;

        display();
    }

    private void display() {
        lblUsername.setText(user.getUserName());
        lblFullname.setText(user.getName());
        lblEmail.setText(user.getEmail());

        if (user.isEnable()) {
            btnEnable.setBackground(primary.COLOR.enable_green);

            btnEnable.setText("Disable");

        } else {
            btnEnable.setBackground(primary.COLOR.disable_gray);

            btnEnable.setText("Enable");

        }
        
        btnEnable.setForeground(primary.COLOR.foreground_white);
        btnEnable.setFont(primary.FONT.tableFontDefault(15));
        btnDelete.setForeground(primary.COLOR.foreground_white);
        btnDelete.setFont(primary.FONT.tableFontDefault(15));
        
        this.setBackground(primary.COLOR.background_secondary);
        
        if (index % 2 == 0) {
            this.setBackground(new Color(204, 230, 192));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnEnable = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 51));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(200, 23));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 23));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        btnEnable.setBackground(new java.awt.Color(255, 51, 0));
        btnEnable.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        btnEnable.setText("Disable");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });
        jPanel3.add(btnEnable);

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);

        add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        lblFullname.setFont(new java.awt.Font("Liberation Mono", 0, 12)); // NOI18N
        lblFullname.setText("Fullname");
        jPanel4.add(lblFullname);

        lblUsername.setFont(new java.awt.Font("Liberation Mono", 0, 12)); // NOI18N
        lblUsername.setText("User name");
        jPanel4.add(lblUsername);

        lblEmail.setFont(new java.awt.Font("Liberation Mono", 0, 12)); // NOI18N
        lblEmail.setText("Email");
        jPanel4.add(lblEmail);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
       user.setEnable(!user.isEnable());
       try{
            controller.updateUser(user);
            
       }catch(SQLException e){
           e.printStackTrace();
           
       }
       display();
       
    }//GEN-LAST:event_btnEnableActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            controller.deleteUser(user);
            listener.onDeleteUser(this);
        } catch (SQLException e) {
            e.printStackTrace();

        }
     
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnable;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
