/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.panels.employee_panel.profile;

import data.controllers.EmployeeController;
import data.model.Employee;
import data.model.Employee_PersonalInfo;
import otherclasses.UtilClass;
import themes.Theme;
import java.sql.SQLException;

/**
 *
 * @author root
 */
public class EmployeeProfilePanel extends javax.swing.JPanel {
    
    

    /**
     * Creates new form EmployeePanel
     */
    
    Employee employee;
    Employee_PersonalInfo personalInfo;
    
    EmployeeController controller = new EmployeeController();
    public EmployeeProfilePanel(Employee employee) {
        
        initComponents();
        this.employee = employee;
        personalInfo = employee.getPersonalInfo();
        init();
    }
    
    
    private void init(){
        //set data
        lblFirstname.setText(UtilClass.checkValue(employee.getFirstName()));
        lblLastname.setText(UtilClass.checkValue(employee.getLastName()));
        lblMiddlename.setText(UtilClass.checkValue(employee.getMiddleName()));
        lblNameExt.setText(UtilClass.checkValue(employee.getNameExtension()));
        lblGender.setText(UtilClass.checkValue(employee.getGender()));
        lblPosition.setText(UtilClass.checkValue(employee.getPosition().getName()));
        lblBirthDate.setText(UtilClass.convertDate(employee.getBirthDate()));
        lblPOB.setText(UtilClass.checkValue(employee.getPlaceOfBirth()));
        lblCreatedAt.setText(employee.getCreated_at().toString());
        lblUpdatedAt.setText(employee.getLast_updated().toString());
        
        lblCitizenship.setText(UtilClass.checkValue(personalInfo.getCitizenship()));
        lblCivilStatus.setText(UtilClass.checkValue(personalInfo.getCivilStatus()));
        lblBloodType.setText(UtilClass.checkValue(personalInfo.getBloodType()));
        lblHeight.setText(UtilClass.checkValue(personalInfo.getHeight()));
        lblWeight.setText(UtilClass.checkValue(personalInfo.getWeight()));
        lblGsis.setText(UtilClass.checkValue(personalInfo.getGsis()));
        lblSss.setText(UtilClass.checkValue(personalInfo.getSss()));
        lblPhilHealth.setText(UtilClass.checkValue(personalInfo.getPhilHealth()));
        lblPagIbig.setText(UtilClass.checkValue(personalInfo.getPagIbig()));
        lblTin.setText(UtilClass.checkValue(personalInfo.getTin()));
        lblCellphone.setText(UtilClass.checkValue(personalInfo.getCellphoneNumber()));
        lblTelephone.setText(UtilClass.checkValue(personalInfo.getTelephoneNumber()));
        lblEmail.setText(UtilClass.checkValue(personalInfo.getEmail()));
        lblCurrent.setText(UtilClass.checkValue(personalInfo.getCurrentAddress()));
        lblPermanent.setText(UtilClass.checkValue(personalInfo.getPermanentAddress()));
        
        
        
    }
    
    
    public void refreshEmployee(String id){
        try{
             employee= controller.getEmployee(id);
             init();
        }catch(SQLException e){
            e.printStackTrace();
        }  
    
    }

    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jLabel4 = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jLabel6 = new javax.swing.JLabel();
        lblMiddlename = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jLabel8 = new javax.swing.JLabel();
        lblNameExt = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jSplitPane8 = new javax.swing.JSplitPane();
        jLabel16 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        jLabel10 = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jSplitPane6 = new javax.swing.JSplitPane();
        jLabel12 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        jSplitPane7 = new javax.swing.JSplitPane();
        jLabel14 = new javax.swing.JLabel();
        lblPOB = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jSplitPane24 = new javax.swing.JSplitPane();
        jLabel49 = new javax.swing.JLabel();
        lblCreatedAt = new javax.swing.JLabel();
        jSplitPane25 = new javax.swing.JSplitPane();
        jLabel51 = new javax.swing.JLabel();
        lblUpdatedAt = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jSplitPane9 = new javax.swing.JSplitPane();
        jLabel19 = new javax.swing.JLabel();
        lblCitizenship = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jSplitPane10 = new javax.swing.JSplitPane();
        jLabel21 = new javax.swing.JLabel();
        lblCivilStatus = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jSplitPane11 = new javax.swing.JSplitPane();
        jLabel23 = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jSplitPane12 = new javax.swing.JSplitPane();
        jLabel25 = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jSplitPane13 = new javax.swing.JSplitPane();
        jLabel27 = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jSplitPane14 = new javax.swing.JSplitPane();
        jLabel29 = new javax.swing.JLabel();
        lblGsis = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jSplitPane15 = new javax.swing.JSplitPane();
        jLabel31 = new javax.swing.JLabel();
        lblSss = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jSplitPane16 = new javax.swing.JSplitPane();
        jLabel33 = new javax.swing.JLabel();
        lblPhilHealth = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jSplitPane17 = new javax.swing.JSplitPane();
        jLabel35 = new javax.swing.JLabel();
        lblPagIbig = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jSplitPane18 = new javax.swing.JSplitPane();
        jLabel37 = new javax.swing.JLabel();
        lblTin = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jSplitPane19 = new javax.swing.JSplitPane();
        jLabel39 = new javax.swing.JLabel();
        lblCellphone = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jSplitPane20 = new javax.swing.JSplitPane();
        jLabel41 = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jSplitPane21 = new javax.swing.JSplitPane();
        jLabel43 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jSplitPane22 = new javax.swing.JSplitPane();
        jLabel45 = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jSplitPane23 = new javax.swing.JSplitPane();
        jLabel47 = new javax.swing.JLabel();
        lblPermanent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(719, 1000));
        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(Theme.PRIMARY.COLOR.background_secondary);
        jPanel1.setLayout(new java.awt.GridLayout(22, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(204, 230, 192));
        jLabel1.setFont(Theme.PRIMARY.FONT.big(22)
        );
        jLabel1.setText("Basic Information");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel2.setText("Firstname:");
        jSplitPane1.setLeftComponent(jLabel2);

        lblFirstname.setText("--");
        jSplitPane1.setRightComponent(lblFirstname);

        jPanel4.add(jSplitPane1);

        jPanel3.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane2.setDividerLocation(120);
        jSplitPane2.setDividerSize(0);
        jSplitPane2.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel4.setText("Lastname:");
        jSplitPane2.setLeftComponent(jLabel4);

        lblLastname.setText("--");
        jSplitPane2.setRightComponent(lblLastname);

        jPanel7.add(jSplitPane2);

        jPanel6.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(jPanel8);

        jPanel1.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane3.setDividerLocation(120);
        jSplitPane3.setDividerSize(0);
        jSplitPane3.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel6.setText("MiddleName:");
        jSplitPane3.setLeftComponent(jLabel6);

        lblMiddlename.setText("--");
        jSplitPane3.setRightComponent(lblMiddlename);

        jPanel10.add(jSplitPane3);

        jPanel9.add(jPanel10);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));
        jPanel9.add(jPanel11);

        jPanel1.add(jPanel9);

        jPanel12.setBackground(new java.awt.Color(153, 153, 255));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane4.setDividerLocation(120);
        jSplitPane4.setDividerSize(0);
        jSplitPane4.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel8.setText("NameExt:");
        jSplitPane4.setLeftComponent(jLabel8);

        lblNameExt.setText("--");
        jSplitPane4.setRightComponent(lblNameExt);

        jPanel13.add(jSplitPane4);

        jPanel12.add(jPanel13);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane8.setDividerLocation(110);
        jSplitPane8.setDividerSize(0);
        jSplitPane8.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel16.setText("Gender");
        jSplitPane8.setLeftComponent(jLabel16);

        lblGender.setText("--");
        jSplitPane8.setRightComponent(lblGender);

        jPanel14.add(jSplitPane8);

        jPanel12.add(jPanel14);

        jPanel1.add(jPanel12);

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(1, 2));

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane5.setDividerLocation(120);
        jSplitPane5.setDividerSize(0);
        jSplitPane5.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel10.setText("BirthDate:");
        jSplitPane5.setLeftComponent(jLabel10);

        lblBirthDate.setText("--");
        jSplitPane5.setRightComponent(lblBirthDate);

        jPanel16.add(jSplitPane5);

        jPanel15.add(jPanel16);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane6.setDividerLocation(110);
        jSplitPane6.setDividerSize(0);
        jSplitPane6.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel12.setText("Position");
        jSplitPane6.setLeftComponent(jLabel12);

        lblPosition.setText("--");
        jSplitPane6.setRightComponent(lblPosition);

        jPanel17.add(jSplitPane6);

        jPanel15.add(jPanel17);

        jPanel1.add(jPanel15);

        jSplitPane7.setDividerLocation(120);
        jSplitPane7.setDividerSize(0);
        jSplitPane7.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Liberation Mono", 1, 12)); // NOI18N
        jLabel14.setText("Place of Birth:");
        jSplitPane7.setLeftComponent(jLabel14);

        lblPOB.setText("--");
        jSplitPane7.setRightComponent(lblPOB);

        jPanel1.add(jSplitPane7);

        jPanel44.setOpaque(false);
        jPanel44.setLayout(new java.awt.GridLayout(1, 2));

        jSplitPane24.setDividerLocation(120);
        jSplitPane24.setDividerSize(0);
        jSplitPane24.setOpaque(false);

        jLabel49.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel49.setText("Created at:");
        jSplitPane24.setLeftComponent(jLabel49);

        lblCreatedAt.setText("--");
        jSplitPane24.setRightComponent(lblCreatedAt);

        jPanel44.add(jSplitPane24);

        jSplitPane25.setDividerLocation(120);
        jSplitPane25.setDividerSize(0);
        jSplitPane25.setOpaque(false);

        jLabel51.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel51.setText("Last Updated:");
        jSplitPane25.setLeftComponent(jLabel51);

        lblUpdatedAt.setText("--");
        jSplitPane25.setRightComponent(lblUpdatedAt);

        jPanel44.add(jSplitPane25);

        jPanel1.add(jPanel44);

        jPanel18.setBackground(new java.awt.Color(153, 153, 255));
        jPanel18.setOpaque(false);
        jPanel18.setLayout(new java.awt.GridLayout(1, 2));

        jPanel20.setOpaque(false);
        jPanel20.setLayout(new java.awt.GridLayout(1, 0));
        jPanel18.add(jPanel20);

        jPanel1.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(153, 153, 255));
        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jLabel18.setBackground(new java.awt.Color(204, 230, 192));
        jLabel18.setFont(Theme.PRIMARY.FONT.big(22)
        );
        jLabel18.setText("Additional Information");
        jLabel18.setOpaque(true);
        jPanel19.add(jLabel18);

        jPanel1.add(jPanel19);

        jPanel21.setBackground(new java.awt.Color(153, 153, 255));
        jPanel21.setOpaque(false);
        jPanel21.setLayout(new java.awt.GridLayout(1, 2));

        jPanel22.setOpaque(false);
        jPanel22.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane9.setDividerLocation(120);
        jSplitPane9.setDividerSize(0);
        jSplitPane9.setOpaque(false);

        jLabel19.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel19.setText("Citizenship:");
        jSplitPane9.setLeftComponent(jLabel19);

        lblCitizenship.setText("--");
        jSplitPane9.setRightComponent(lblCitizenship);

        jPanel22.add(jSplitPane9);

        jPanel21.add(jPanel22);

        jPanel23.setOpaque(false);
        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane10.setDividerLocation(120);
        jSplitPane10.setDividerSize(0);
        jSplitPane10.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel21.setText("Civil Status:");
        jSplitPane10.setLeftComponent(jLabel21);

        lblCivilStatus.setText("--");
        jSplitPane10.setRightComponent(lblCivilStatus);

        jPanel23.add(jSplitPane10);

        jPanel21.add(jPanel23);

        jPanel1.add(jPanel21);

        jPanel24.setOpaque(false);
        jPanel24.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane11.setDividerLocation(120);
        jSplitPane11.setDividerSize(0);
        jSplitPane11.setOpaque(false);

        jLabel23.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel23.setText("Blood Type:");
        jSplitPane11.setLeftComponent(jLabel23);

        lblBloodType.setText("--");
        jSplitPane11.setRightComponent(lblBloodType);

        jPanel24.add(jSplitPane11);

        jPanel1.add(jPanel24);

        jPanel25.setBackground(new java.awt.Color(153, 153, 255));
        jPanel25.setOpaque(false);
        jPanel25.setLayout(new java.awt.GridLayout(1, 2));

        jPanel26.setOpaque(false);
        jPanel26.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane12.setDividerLocation(120);
        jSplitPane12.setDividerSize(0);
        jSplitPane12.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel25.setText("Height:");
        jSplitPane12.setLeftComponent(jLabel25);

        lblHeight.setText("--");
        jSplitPane12.setRightComponent(lblHeight);

        jPanel26.add(jSplitPane12);

        jPanel25.add(jPanel26);

        jPanel27.setOpaque(false);
        jPanel27.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane13.setDividerLocation(120);
        jSplitPane13.setDividerSize(0);
        jSplitPane13.setOpaque(false);

        jLabel27.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel27.setText("Weight:");
        jSplitPane13.setLeftComponent(jLabel27);

        lblWeight.setText("--");
        jSplitPane13.setRightComponent(lblWeight);

        jPanel27.add(jSplitPane13);

        jPanel25.add(jPanel27);

        jPanel1.add(jPanel25);

        jPanel28.setBackground(new java.awt.Color(153, 153, 255));
        jPanel28.setOpaque(false);
        jPanel28.setLayout(new java.awt.GridLayout(1, 2));

        jPanel29.setOpaque(false);
        jPanel29.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane14.setDividerLocation(120);
        jSplitPane14.setDividerSize(0);
        jSplitPane14.setOpaque(false);

        jLabel29.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel29.setText("GSIS:");
        jSplitPane14.setLeftComponent(jLabel29);

        lblGsis.setText("--");
        jSplitPane14.setRightComponent(lblGsis);

        jPanel29.add(jSplitPane14);

        jPanel28.add(jPanel29);

        jPanel30.setOpaque(false);
        jPanel30.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane15.setDividerLocation(120);
        jSplitPane15.setDividerSize(0);
        jSplitPane15.setOpaque(false);

        jLabel31.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel31.setText("SSS:");
        jSplitPane15.setLeftComponent(jLabel31);

        lblSss.setText("--");
        jSplitPane15.setRightComponent(lblSss);

        jPanel30.add(jSplitPane15);

        jPanel28.add(jPanel30);

        jPanel1.add(jPanel28);

        jPanel31.setBackground(new java.awt.Color(153, 153, 255));
        jPanel31.setOpaque(false);
        jPanel31.setLayout(new java.awt.GridLayout(1, 2));

        jPanel32.setOpaque(false);
        jPanel32.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane16.setDividerLocation(120);
        jSplitPane16.setDividerSize(0);
        jSplitPane16.setOpaque(false);

        jLabel33.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel33.setText("PhilHealth:");
        jSplitPane16.setLeftComponent(jLabel33);

        lblPhilHealth.setText("--");
        jSplitPane16.setRightComponent(lblPhilHealth);

        jPanel32.add(jSplitPane16);

        jPanel31.add(jPanel32);

        jPanel33.setOpaque(false);
        jPanel33.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane17.setDividerLocation(120);
        jSplitPane17.setDividerSize(0);
        jSplitPane17.setOpaque(false);

        jLabel35.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel35.setText("Pag-Ibig:");
        jSplitPane17.setLeftComponent(jLabel35);

        lblPagIbig.setText("--");
        jSplitPane17.setRightComponent(lblPagIbig);

        jPanel33.add(jSplitPane17);

        jPanel31.add(jPanel33);

        jPanel1.add(jPanel31);

        jPanel34.setBackground(new java.awt.Color(153, 153, 255));
        jPanel34.setOpaque(false);
        jPanel34.setLayout(new java.awt.GridLayout(1, 2));

        jPanel35.setOpaque(false);
        jPanel35.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane18.setDividerLocation(120);
        jSplitPane18.setDividerSize(0);
        jSplitPane18.setOpaque(false);

        jLabel37.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel37.setText("Tin:");
        jSplitPane18.setLeftComponent(jLabel37);

        lblTin.setText("--");
        jSplitPane18.setRightComponent(lblTin);

        jPanel35.add(jSplitPane18);

        jPanel34.add(jPanel35);

        jPanel1.add(jPanel34);

        jPanel36.setBackground(new java.awt.Color(153, 153, 255));
        jPanel36.setOpaque(false);
        jPanel36.setLayout(new java.awt.GridLayout(1, 2));

        jPanel37.setOpaque(false);
        jPanel37.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane19.setDividerLocation(120);
        jSplitPane19.setDividerSize(0);
        jSplitPane19.setOpaque(false);

        jLabel39.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel39.setText("Cellphone:");
        jSplitPane19.setLeftComponent(jLabel39);

        lblCellphone.setText("--");
        jSplitPane19.setRightComponent(lblCellphone);

        jPanel37.add(jSplitPane19);

        jPanel36.add(jPanel37);

        jPanel38.setOpaque(false);
        jPanel38.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane20.setDividerLocation(120);
        jSplitPane20.setDividerSize(0);
        jSplitPane20.setOpaque(false);

        jLabel41.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel41.setText("Telephone");
        jSplitPane20.setLeftComponent(jLabel41);

        lblTelephone.setText("--");
        jSplitPane20.setRightComponent(lblTelephone);

        jPanel38.add(jSplitPane20);

        jPanel36.add(jPanel38);

        jPanel1.add(jPanel36);

        jPanel39.setBackground(new java.awt.Color(153, 153, 255));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new java.awt.GridLayout(1, 2));

        jPanel40.setOpaque(false);
        jPanel40.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane21.setDividerLocation(120);
        jSplitPane21.setDividerSize(0);
        jSplitPane21.setOpaque(false);

        jLabel43.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel43.setText("Email:");
        jSplitPane21.setLeftComponent(jLabel43);

        lblEmail.setText("--");
        jSplitPane21.setRightComponent(lblEmail);

        jPanel40.add(jSplitPane21);

        jPanel39.add(jPanel40);

        jPanel1.add(jPanel39);

        jPanel41.setBackground(new java.awt.Color(153, 153, 255));
        jPanel41.setOpaque(false);
        jPanel41.setLayout(new java.awt.GridLayout(1, 2));

        jPanel42.setOpaque(false);
        jPanel42.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane22.setDividerLocation(145);
        jSplitPane22.setDividerSize(0);
        jSplitPane22.setOpaque(false);

        jLabel45.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel45.setText("Current Address:");
        jSplitPane22.setLeftComponent(jLabel45);

        lblCurrent.setText("--");
        jSplitPane22.setRightComponent(lblCurrent);

        jPanel42.add(jSplitPane22);

        jPanel41.add(jPanel42);

        jPanel1.add(jPanel41);

        jPanel43.setOpaque(false);
        jPanel43.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane23.setDividerLocation(145);
        jSplitPane23.setDividerSize(0);
        jSplitPane23.setOpaque(false);

        jLabel47.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel47.setText("Permanent Address:");
        jSplitPane23.setLeftComponent(jLabel47);

        lblPermanent.setText("--");
        jSplitPane23.setRightComponent(lblPermanent);

        jPanel43.add(jSplitPane23);

        jPanel1.add(jPanel43);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane10;
    private javax.swing.JSplitPane jSplitPane11;
    private javax.swing.JSplitPane jSplitPane12;
    private javax.swing.JSplitPane jSplitPane13;
    private javax.swing.JSplitPane jSplitPane14;
    private javax.swing.JSplitPane jSplitPane15;
    private javax.swing.JSplitPane jSplitPane16;
    private javax.swing.JSplitPane jSplitPane17;
    private javax.swing.JSplitPane jSplitPane18;
    private javax.swing.JSplitPane jSplitPane19;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane20;
    private javax.swing.JSplitPane jSplitPane21;
    private javax.swing.JSplitPane jSplitPane22;
    private javax.swing.JSplitPane jSplitPane23;
    private javax.swing.JSplitPane jSplitPane24;
    private javax.swing.JSplitPane jSplitPane25;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane7;
    private javax.swing.JSplitPane jSplitPane8;
    private javax.swing.JSplitPane jSplitPane9;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCellphone;
    private javax.swing.JLabel lblCitizenship;
    private javax.swing.JLabel lblCivilStatus;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGsis;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMiddlename;
    private javax.swing.JLabel lblNameExt;
    private javax.swing.JLabel lblPOB;
    private javax.swing.JLabel lblPagIbig;
    private javax.swing.JLabel lblPermanent;
    private javax.swing.JLabel lblPhilHealth;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSss;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTin;
    private javax.swing.JLabel lblUpdatedAt;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables
}
