/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.panels;

import data.controllers.EmployeeController;
import data.controllers.PersonnelController;
import data.model.Personnel;
import java.awt.GridLayout;
import java.util.List;

/**
 *
 * @author root
 */
public class PersonnelPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonnelPanel
     */
    
    private List<Personnel> personnels;
    PersonnelController controller = new PersonnelController();
    public PersonnelPanel() {
        initComponents();
        
        try{
            
            controller.addPersonnels();
            
            personnels = controller.getPersonnels();
            
            createPersonnelPanel();
        }catch(java.sql.SQLException e){
            e.printStackTrace();
        }
        
    }

    private void createPersonnelPanel() {
         mainContainer.setLayout(new GridLayout(4,0));
        for (Personnel item : personnels) {
            javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
            jPanel2.setOpaque(false);
            
            javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
            jLabel1.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText(item.getPosition().getName());
           
            javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
            jLabel2.setText(item.getEmployee()==null?"N/A" : item.getEmployee().getFullname());
            jPanel2.add(jLabel2);

            javax.swing.JButton jButton1 = new javax.swing.JButton();
            jButton1.setText("Change");
            jPanel2.add(jButton1);

           
           

            javax.swing.JPanel jPanel1 = new javax.swing.JPanel();

            jPanel1.setOpaque(false);
            jPanel1.setLayout(new java.awt.GridLayout(2, 0));
            
            jPanel1.add(jLabel1);
            jPanel1.add(jPanel2);
            
           mainContainer.add(jPanel1);

       




        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        jPanelfiller = new javax.swing.JPanel();
        jPanelfiller1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        mainContainer.setOpaque(false);
        add(mainContainer, java.awt.BorderLayout.CENTER);

        jPanelfiller.setPreferredSize(new java.awt.Dimension(110, 80));
        add(jPanelfiller, java.awt.BorderLayout.NORTH);

        jPanelfiller1.setPreferredSize(new java.awt.Dimension(110, 80));
        add(jPanelfiller1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelfiller;
    private javax.swing.JPanel jPanelfiller1;
    private javax.swing.JPanel mainContainer;
    // End of variables declaration//GEN-END:variables
}
