/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.panels;

import data.controllers.UserController;
import data.model.User;
import frames.components.UserItem;
import frames.listener.UserItemListener;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import themes.Theme;

/**
 *
 * @author root
 */
public class UserPanel extends javax.swing.JPanel implements UserItemListener {

    /**
     * Creates new form UserPanel
     */
    UserController controller = new UserController();
    List<User> users ;

    public UserPanel() {
        initComponents();

        init();
    }

    private void init() {

        jButton2.setVisible(false);
        jButton3.setVisible(false);
        try {
            users = controller.getAllUsers();
            displayUsers(users);
        } catch (SQLException e) {

        }

    }

    private void displayUsers(List<User> users) {
         panelUserList.removeAll();
        panelUserList.repaint();
        panelUserList.revalidate();


        int rows;

        if (users.size() < 10) {
            rows = 10;
        } else {
            rows = users.size();
        }
        panelUserList.setLayout(new GridLayout(rows, 0));

        UserItem[] userItem = new UserItem[rows];

        int i = 0;
        for (User _user : users) {
            userItem[i] = new UserItem(this, i, _user);
            panelUserList.add(userItem[i]);
            i++;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSplitPane2 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelUserList = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(531, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(4, 0, 10, 10));
        jPanel1.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(5, 0));

        jLabel1.setFont(Theme.PRIMARY.FONT.tableFontDefault(14)
        );
        jLabel1.setText("Search");
        jPanel4.add(jLabel1);
        jPanel4.add(txtSearch);

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setDividerSize(0);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jSplitPane2.setRightComponent(jButton1);

        jLabel2.setText(" ");
        jSplitPane2.setLeftComponent(jLabel2);

        jPanel4.add(jSplitPane2);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(30);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOpaque(false);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont( Theme.PRIMARY.FONT.defaultFont(15));
        jButton3.setText("Enable");
        jPanel6.add(jButton3);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont( Theme.PRIMARY.FONT.defaultFont(15));
        jButton2.setText("Delete");
        jPanel6.add(jButton2);

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(204, 230, 192));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jLabel4.setFont(new java.awt.Font("Liberation Mono", 1, 12)); // NOI18N
        jLabel4.setText("Fullname");
        jPanel8.add(jLabel4);

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 1, 12)); // NOI18N
        jLabel3.setText("Username");
        jPanel8.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Liberation Mono", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        jPanel8.add(jLabel5);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel2);

        jSplitPane1.setLeftComponent(jPanel7);

        panelUserList.setBackground(new java.awt.Color(255, 255, 255));
        panelUserList.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane1.setBottomComponent(panelUserList);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        User _user = searchUser(txtSearch.getText());
        List<User> user= new ArrayList<>();
        user.add(_user);
        
        if(_user!=null ){
            displayUsers(user);
        }else displayUsers(this.users) ;
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel panelUserList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onDeleteUser(UserItem userItem) {
        panelUserList.remove(userItem);
        panelUserList.repaint();
        panelUserList.revalidate();

    }
    
    private User searchUser(String str){
        
        for(User user:this.users){
            System.out.println(user.getUserName());
            if(user.getUserName().toLowerCase().equals(str.toLowerCase())){
                System.out.println(user.getUserName());
                return user;
                
            }
        }
        return null;
    }
}
