/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames.components.windows;

import data.controllers.LeaveFormController;
import data.model.EmployeeServiceCredit;
import frames.MainFrame;
import frames.components.windows.comp.W_EmployeeServiceCreditItem;
import frames.components.windows.listener.EmployeeServiceCreditItemListener;
import frames.panels.employee_panel.LeaveFormPanel;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import otherclasses.UtilClass;

/**
 *
 * @author root
 */
public class LeaveServiceCreditWindow extends javax.swing.JDialog implements EmployeeServiceCreditItemListener {

    /**
     * Creates new form LeaveServiceCreditWindow
     */
    MainFrame root;
    List<EmployeeServiceCredit> inUseServiceCredits;
    List<EmployeeServiceCredit> unUsedServiceCredits;

    LeaveFormController controller = new LeaveFormController();

    EmployeeServiceCredit employeeServiceCredit;

    int totalCredit;
    int useCredit;
    private LeaveFormPanel parent;

    public LeaveServiceCreditWindow() {
        initComponents();
    }

    /**
     * Creates new form LeaveServiceCreditWindow
     *
     * @param root to disable parent frame once this window is opened
     * @param parent get parent reference(LeaveForm Panel)
     * @param inUseServiceCredits used service credits
     * @param unUsedServiceCredits unused service credits
     */
    public void setFrame(MainFrame root, LeaveFormPanel parent, List<EmployeeServiceCredit> inUseServiceCredits, List<EmployeeServiceCredit> unUsedServiceCredits) {
        this.unUsedServiceCredits = unUsedServiceCredits;
        
      
        this.parent = parent;
        this.inUseServiceCredits = inUseServiceCredits;
        updateLabel();

        this.root = root;
        populatePanel();
    }

    private void updateLabel() {
        totalCredit = UtilClass.getTotalCredits(inUseServiceCredits);
        useCredit = UtilClass.getTotalUsedCredits(inUseServiceCredits);

        lblTotalCredits.setText("(" + useCredit + "/" + totalCredit + ")");
    }

    

    public void updateList(String employeeId, int serviceCreditId) {
        try {
       

            inUseServiceCredits.add(controller.getEmployeeServiceCredit(employeeId, serviceCreditId));
        
            populatePanel();
            updateLabel();
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }

    }

    private void populatePanel() {
        panelList.removeAll();
        panelList.repaint();
        panelList.validate();
        int row = inUseServiceCredits.size();
        if (row < 6) {
            row = 5;
        }

        panelList.setLayout(new GridLayout(row, 0));
        for (EmployeeServiceCredit item : inUseServiceCredits) {
            W_EmployeeServiceCreditItem panelItem = new W_EmployeeServiceCreditItem(this, item);
            panelItem.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    W_EmployeeServiceCreditItem item = (W_EmployeeServiceCreditItem) e.getSource();
                    employeeServiceCredit = item.getEmployeeServiceCredit();
                  
                }
            });

            panelList.add(panelItem);
        }

    }
    
    
    public EmployeeServiceCredit getReference(EmployeeServiceCredit item){
         for (EmployeeServiceCredit _item : inUseServiceCredits) {
//             System.out.println(_item == item);
//             if(_item == item){
//                 return _item;
//             }
        System.out.println(_item.getServiceCredit().getMemorandum()+" Numner of days: "+_item.getNo_of_days());
         }
         return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelList = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblTotalCredits = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 383));

        panelList.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelListLayout = new javax.swing.GroupLayout(panelList);
        panelList.setLayout(panelListLayout);
        panelListLayout.setHorizontalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        panelListLayout.setVerticalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(193, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Service Credits Used");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, java.awt.BorderLayout.EAST);

        lblTotalCredits.setText("(0/0)");
        jPanel1.add(lblTotalCredits, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(70, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setMinimumSize(new java.awt.Dimension(70, 100));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, java.awt.BorderLayout.WEST);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(260, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setPreferredSize(new java.awt.Dimension(260, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        root.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddServiceCreditWindow add = new AddServiceCreditWindow();
        add.setFramefromAdd(root, this, controller.getAvailableLeaveFormServiceCredits(unUsedServiceCredits, inUseServiceCredits));
        add.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        parent.updateLeaveForm(inUseServiceCredits);
        root.setEnabled(true);
        dispose();
//        if(employeeServiceCredit ==null){
//            JOptionPane.showMessageDialog(this, "No Item Selected");
//        }else{
//            this.updateList(employeeServiceCredit);
//        }
        //  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveServiceCreditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveServiceCreditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveServiceCreditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveServiceCreditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveServiceCreditWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalCredits;
    private javax.swing.JPanel panelList;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSpinnerClick(boolean isAdd,EmployeeServiceCredit item) {
     
        if (isAdd) {
            useCredit += 1;

        } else {
            useCredit -= 1;
        }

        updateLabel();
    }
}
