/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.components.windows.comp;

import data.model.EmployeeServiceCredit;

/**
 *
 * @author root
 */
public class W_EmployeeServiceCreditItem extends javax.swing.JPanel {

    /**
     * Creates new form W_EmployeeServiceCreditItem
     */
    EmployeeServiceCredit employeeServiceCredit;
    public W_EmployeeServiceCreditItem(EmployeeServiceCredit employeeServiceCredit) {
        this.employeeServiceCredit = employeeServiceCredit;
        initComponents();
         setUpPanel();
    }
    
    private void setUpPanel(){
        lblOrderNumber.setText(employeeServiceCredit.getServiceCredit().getOrderNo());
        lblMemorandum.setText(employeeServiceCredit.getServiceCredit().getMemorandum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrderNumber = new javax.swing.JLabel();
        lblMemorandum = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();

        setLayout(new java.awt.BorderLayout());

        lblOrderNumber.setText("Order Number");
        lblOrderNumber.setPreferredSize(new java.awt.Dimension(100, 17));
        add(lblOrderNumber, java.awt.BorderLayout.WEST);

        lblMemorandum.setText("Memorandum");
        add(lblMemorandum, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());
        jPanel1.add(jSlider1);

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblMemorandum;
    private javax.swing.JLabel lblOrderNumber;
    // End of variables declaration//GEN-END:variables
}
